
SELECT DISTINCT LC1.LCT_PRENOM, LC1.LCT_NOM, LC2.LCT_PRENOM, LC2.LCT_NOM,
AP1.APT_NUM, AP2.APT_NUM
FROM S_IMO.T_LOCATAIRE_LCT LC1
INNER JOIN S_IMO.T_APPARTEMENT_APT AP1
ON LC1.APT_NUM = AP1.APT_NUM
CROSS JOIN
S_IMO.T_LOCATAIRE_LCT LC2
INNER JOIN S_IMO.T_APPARTEMENT_APT AP2
ON LC2.APT_NUM = AP2.APT_NUM
WHERE AP1.APT_NUM <> AP2.APT_NUM
AND LC1.LCT_NUM <> LC2.LCT_NUM
AND AP1.APT_SURFACE = AP2.APT_SURFACE
AND AP1.APT_IMEUBLE = AP2.APT_IMEUBLE
AND LC1.LCT_NUM > LC2.LCT_NUM;



SELECT DISTINCT LC1.LCT_PRENOM, LC1.LCT_NOM, AP1.APT_NUM, LC2.LCT_PRENOM,
LC2.LCT_NOM, AP2.APT_NUM
FROM S_IMO.T_LOCATAIRE_LCT LC1
INNER JOIN S_IMO.T_APPARTEMENT_APT AP1
ON LC1.APT_NUM = AP1.APT_NUM
INNER JOIN S_IMO.T_LOCATAIRE_LCT LC2
ON LC1.LCT_NUM <> LC2.LCT_NUM
AND LC1.LCT_NUM > LC2.LCT_NUM
INNER JOIN S_IMO.T_APPARTEMENT_APT AP2
ON LC2.APT_NUM = AP2.APT_NUM
AND AP1.APT_NUM <> AP2.APT_NUM
AND AP1.APT_SURFACE = AP2.APT_SURFACE
AND AP1.APT_IMEUBLE = AP2.APT_IMEUBLE;
