SELECT FRM.FRM_ID, FRM_NOM
FROM
S_NEWS.T_NEWS_NEW NEW
INNER JOIN S_NEWS.T_FORUM_FRM FRM
ON NEW.FRM_ID = FRM.FRM_ID
WHERE NOT EXISTS (SELECT *
FROM
S_NEWS.T_UTILISATEUR_USR USR
INNER JOIN S_NEWS.T_J_INSCRIS_NEWS.ISC ISC
ON USR.USR_ID = ISC.USR_ID
WHERE NEW.USR_ID = USR.USR_ID);



SELECT FRM.FRM_ID, FRM.FRM_NOM,
SUM(FIC.FIC_TAILLE_O) AS TAILLE_OCTET
FROM
S_NEWS.T_NEWS_NEW NEW
LEFT OUTER JOIN S_NEWS.T_FICHIER_FIC FIC
ON NEW.NEW_ID = FIC.NEW_ID
INNER JOIN S_NEWS.T_FORUM_FRM FRM
ON NEW.FRM_ID = FRM.FRM_ID
GROUP BY FRM.FRM_ID, FRM.FRM_NOM
HAVING SUM(FIC.FIC_TAILLE_O) =
( SELECT MAX(TAILLE_OCTET) AS
FROM ( SELECT SUM(FIC.FIC_TAILLE_O) AS TAILLE_OCTET, NEW.FRM_ID
FROM
S_NEWS.T_FICHIER_FIC FIC
INNER JOIN S_NEWS.T_NEWS_NEW NEW
ON FIC.NEW_ID = NEW.NEW_ID
GROUP BY NEW.FRM_ID
);


SELECT FRM.FRM_ID, FRM.FRM_NOM, COUNT(NEW_ID) AS NEW_NOMBRE,
USR.USR_ID, USR.USR_NOM
FROM
S_NEWS.T_NEWS_NEW NEW
LEFT OUTER JOIN S_NEWS.T_UTILISATEUR_USR USR
ON NEW.USR_ID = USR.USR_ID
LEFT OUTER JOIN S_NEWS.T_FORUM_FRM FRM
ON NEW.FRM_ID = FRM.FRM_ID
GROUP BY FRM.FRM_ID, NEW.FRM_ID, FRM.FRM_NOM, USR.USR_ID,
NEW.USR_ID, USR.USR_NOM
HAVING COUNT(NEW_ID) =(SELECT MAX(NEW_NOMBRE)
FROM
(SELECT FM2.FRM_ID, COUNT(NEW_ID) AS NEW_NOMBRE
FROM
S_NEWS.T_NEWS_NEW NW2
LEFT OUTER JOIN S_NEWS.T_UTILISATEUR_USR US2
ON NW2.USR_ID = US2.USR_ID
LEFT OUTER JOIN S_NEWS. S_NEWS.FORUM_FRM FM2
ON NW2.FRM_ID = FM2.FRM_ID
WHERE FM2.FRM_ID = FRM.FRM_ID
GROUP BY FM2.FRM_ID, US2.USR_ID )
GROUP BY FRM_ID);










